### PR TITLE
Add support for groups

### LINKED ISSUE #39: Allow creating lists of project members
We would like to allow lists/groups of project members to be added to this application. The administrator should be able to create these groups and add members to those groups.

The list/group data should be held in a model, something like `ProjectGroup`, which would allow many project members to be manually added by a project administrator after the group was created. These member lists will only be in this `oh-proj-management` application; these lists will not be sent back to the main Open Humans site. There should be a screen to display these groups of users, with some basic detail on each user.

## Acceptance criteria

- Adds a model for member lists / groups like `ProjectGroup`
- View that allows an administrator to create a (named) group and add members to that group
- View that displays all lists/groups with the users in each list/group

### PR DESCRIPTION
**Pull request by shubhangi-chauhan**
Closes #39

### CODE REVIEW

**Comment by shubhangi-chauhan** [comment]
I'm a little confused about whether to call it project groups (groups in a project - could be groups of files / members etc) or member groups (groups comprising of members)

**Comment by rosygupta** [comment]
@shubhangi-chauhan is this PR complete? asking cuz I'll work on annotations then. :)

**Comment by shubhangi-chauhan** [comment]
@mcescalante Thanks for reviewing! :)

@rosygupta I have now moved the member card to its own partial, so adding annotations should be more convenient.

**Comment by rosygupta** [comment]
@shubhangi-chauhan Would you like me to complete this PR? In case you not getting time? :)

**Comment by mcescalante** [comment]
@rosygupta this is actually just waiting for my review, which I'll do shortly 😄

**Comment by rosygupta** [comment]
@mcescalante My bad! :stuck_out_tongue:

**Pull request merged**
