### PR TITLE
WIP Fixes #4 Retrieves and displays project-level information

### LINKED ISSUE #4: Retrieve and display project-level information
Update `HomeView` to ~~use the Open Humans API project information endpoint ([at the bottom of this page](https://www.openhumans.org/direct-sharing/on-site-data-access/#api-project-info)) and retrieve project information.~~

~~Pass this information to context and~~ display the project title (and maybe more information about the project?) in `home.html`

### PR DESCRIPTION
**Pull request by eeshadutta**
WIP   Retrieves and displays project-level information

The HomeView is updated with project information by retrieving information from the model.

image

### CODE REVIEW

**Comment by eeshadutta** [comment]
@madprime @gedankenstuecke @mcescalante  Please review

**Comment by madprime** [comment]
Hi @eeshadutta please put WIP in the PR name itself until you believe it's ready to merge – sorry I may have missed this in a previous PR. (I've edited this PR name accordingly. :smile: )

**Comment by eeshadutta** [comment]
Sure @madprime I'll follow this henceforth.

**Comment by gedankenstuecke** [comment]
So far this includes just the base project details, right? The API-powered version also got all the members of a project and their files. Should this maybe also go into a database model @madprime? The issue would then be to keep the member-list in the `oh-proj-management` up to date.

**Comment by eeshadutta** [comment]
@madprime @gedankenstuecke @mcescalante do you want me to add anything in this?

**Comment by eeshadutta** [comment]
image

@gedankenstuecke  I do not face this problem. Please could you rebase your repository again to the current state of this PR.

**Comment by mcescalante** [comment]
@eeshadutta I am also getting the same error:



I believe this is due to #20 which was merged (after this PR was opened) and adds a migration called `0003_auto_20180222_2041.py` (https://github.com/OpenHumans/oh-proj-management/pull/20/files#diff-0cafc39542d1a9d4a24a8de6b7143468). This merged migration conflicts with your `0003_project_token` migration because they're both 0003.

**Steps to reproduce:**
1. Do a fresh (separate) `git clone git@github.com:OpenHumans/oh-proj-management.git`
2. Do the pipenv setup and run migrations on master branch, make sure the app runs
3. Get this PR and put it in a local branch named `16`: `git fetch origin pull/16/head:16`
4. Check into the PR branch: `git checkout 16`
5. Try running migrations with `pipenv run python manage.py migrate`
When you run the migrations, you should see the same error we are both seeing.

If you would like any help resolving the conflict or reproducing this on your local environment, let me know!

**Comment by eeshadutta** [comment]
@mcescalante  Thanks for the advice. I have done that and have made the necessary changes. Please review.

**Comment by eeshadutta** [comment]
@gedankenstuecke I have made required changes. Please review

**Comment by eeshadutta** [comment]
image
@gedankenstuecke I have made the required changes. Its working now.

**Comment by gedankenstuecke** [comment]
Mh... I guess the issue is that the migration leads to the token-field being empty so the project isn't updated and there's no simple way to set a default for it?

**Comment by gedankenstuecke** [comment]
Great, thanks!

**Pull request merged**
