### PR TITLE
Upgrading Django version to 2.0.2

### PR DESCRIPTION
**Pull request by suba06**
Hello,

This is regarding the issue #2 

Though I am new to your world, I would like to take this 'Outreachy application' opportunity to learn and contribute to the best of my extent.

### CODE REVIEW

**Comment by suba06** [comment]
May I also please know why the requests module is not checked in that is imported in the views? Sorry if this is a silly question. I am following the Django tutorial shared by @madprime and will soon get a grasp on it.

**Comment by madprime** [comment]
Thanks @suba06!

I'm not sure what you mean about the requests module not being checked in. It is listed in the `requirements.txt` file, which you edited.

I've updated the instructions on the README to clarify. In the process, I noticed that an addition related to environment variables was needed to help people run the site locally.

And also to check: are you able to run this site locally? It's important for you to run the site locally and check that your code changes work before you make a pull request.

**Comment by madprime** [comment]
As a result of my changes, there's a conflict that needs to be fixed for this to be merged. I'll let you do this, if you'd like?

Also, I would like to please keep `requirements.txt` in the same order that `pip freeze` produces. (I noticed your proposed change shifts the position of `pytz` as well as bumping version – the version bump seems fine but the positions should remain the same.)

**Comment by suba06** [comment]
Thanks a lot @madprime . Sorry for my minor mistakes. 

Yes. I was able to get the site running locally. The struggle was a good learning to start with. I can now see the steps added. Thanks for it.

I also tried to resolve the merge conflicts after using pip freeze to order it.

**Comment by madprime** [comment]
No problem – hopefully the instructions help! I'm sorry they were there earlier. :)

**Pull request merged**
