### PR TITLE
WIP Fixes#25 Adding Flake8 to the project

### PR DESCRIPTION
**Pull request by eeshadutta**
I have corrected the linting errors in the code and have also added flake8 to the README.md file which contributors can run to fix PEP8 errors before commiting their changes.

### CODE REVIEW

**Comment by eeshadutta** [comment]
@madprime @gedankenstuecke @mcescalante Please review

**Comment by eeshadutta** [comment]
@mcescalante Is there anything I need to change?

**Comment by mcescalante** [comment]
@eeshadutta yeah, apologies, I accidentally hit approve on my first review.

I would appreciate it if you could:

1. Commit the latest `Pipfile.lock` (run `pipenv install` again if yours has no changes when you look at `git status`
2. Update the instructions to just be `flake8` before committing, instead of `flake8 oh_proj_management` in the README

Let me know if you have problems making either of these changes!

**Comment by eeshadutta** [comment]
@mcescalante I have made the changes as suggested by you. Let me know if ther's anything else I need to do.

**Pull request merged**
